######################################################################
# Automatically generated by qmake (3.0) ?? ??? 16 23:14:50 2016
######################################################################

TEMPLATE = app
TARGET = yang
INCLUDEPATH += . src src/core src/parsers src/ui 3rdparty/gumbo-parser/src/

CONFIG += qt c++14 
QT += core gui quick webenginewidgets

QMAKE_CFLAGS += -std=c99

# Input
HEADERS += src/Utils.h \
           src/core/Column.h \
           src/core/Crossword.h \
           src/core/Row.h \
           src/core/Size.h \
           src/parsers/Gumbo.hpp \
           src/parsers/NonogramsCrosswordGalleryParser.h \
           src/parsers/NonogramsParser.h \
           src/ui/Application.h \
           src/ui/CrosswordModel.h \
           3rdparty/gumbo-parser/src/attribute.h \
           3rdparty/gumbo-parser/src/char_ref.h \
           3rdparty/gumbo-parser/src/error.h \
           3rdparty/gumbo-parser/src/gumbo.h \
           3rdparty/gumbo-parser/src/insertion_mode.h \
           3rdparty/gumbo-parser/src/parser.h \
           3rdparty/gumbo-parser/src/string_buffer.h \
           3rdparty/gumbo-parser/src/string_piece.h \
           3rdparty/gumbo-parser/src/tag_enum.h \
           3rdparty/gumbo-parser/src/tag_gperf.h \
           3rdparty/gumbo-parser/src/tag_sizes.h \
           3rdparty/gumbo-parser/src/tag_strings.h \
           3rdparty/gumbo-parser/src/token_type.h \
           3rdparty/gumbo-parser/src/tokenizer.h \
           3rdparty/gumbo-parser/src/tokenizer_states.h \
           3rdparty/gumbo-parser/src/utf8.h \
           3rdparty/gumbo-parser/src/util.h \
           3rdparty/gumbo-parser/src/vector.h 

SOURCES += src/main.cpp \
           src/Utils.cpp \
           src/core/Column.cpp \
           src/core/Crossword.cpp \
           src/core/Row.cpp \
           src/core/Size.cpp \
           src/parsers/NonogramsCrosswordGalleryParser.cpp \
           src/parsers/NonogramsParser.cpp \
           src/ui/Application.cpp \
           src/ui/CrosswordModel.cpp \
           3rdparty/gumbo-parser/src/attribute.c \
           3rdparty/gumbo-parser/src/char_ref.c \
           3rdparty/gumbo-parser/src/error.c \
           3rdparty/gumbo-parser/src/parser.c \
           3rdparty/gumbo-parser/src/string_buffer.c \
           3rdparty/gumbo-parser/src/string_piece.c \
           3rdparty/gumbo-parser/src/tag.c \
           3rdparty/gumbo-parser/src/tokenizer.c \
           3rdparty/gumbo-parser/src/utf8.c \
           3rdparty/gumbo-parser/src/util.c \
           3rdparty/gumbo-parser/src/vector.c 

RESOURCES += src/resources/qml.qrc
